version: '3.8'

services:
  spark:
    build: .
    container_name: spark-stock-analytics
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/spark/gcp/gcp-service-account.json
    volumes:
      - ./app:/app
      - ./gcp/gcp-service-account.json:/opt/spark/gcp/gcp-service-account.json:ro
    command: >
      bash -c "spark-submit --master local[*] stock_analytics.py"
